(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



inputDirectory = "/home/jwb/repos/github-research/MLMetrics/Committers/csvs/";


labels = {"Caffe","CNTK","DL4J","TensorFlow","Theano","Torch7"};


exportDirectory = "/home/jwb/repos/github-research/MLMetrics/Frequency Analysis/";


exportType = ".png"


normalizationN = 1000;


data`big = Import[#,"Data"]&/@FileNames["*.csv",inputDirectory];


g`full =
 ListLogPlot[
  Table[
   Sort[
    data`big[[n]][[All,2]],
    Greater
   ],
   {n,Length@labels}],
  PlotRange->Full,
  PlotLegends->labels,
  AxesLabel->{"Contributor Rank","Number of Commits"},
  ImageSize->Full,
  Joined->True]


g`fullLogLog =
 ListLogLogPlot[
  Table[
   Sort[
    data`big[[n]][[All,2]],
    Greater
   ],
   {n,Length@labels}],
  PlotRange->Full,
  PlotLegends->labels,
  AxesLabel->{"Contributor Rank","Number of Commits"},
  ImageSize->Full,
  Joined->True]


g`fullNorm =
 ListLogPlot[
  Table[
   Sort[
    data`big[[n]][[All,2]],
    Greater
   ],
   {n,Length@labels}],
  PlotRange->Full,
  PlotLegends->labels,
  AxesLabel->{"Contributor Rank","Number of Commits"},
  ImageSize->Full,
  Joined->True,
  DataRange->{1,normalizationN}]


g`fullLogLogNorm =
 ListLogLogPlot[
  Table[
   Sort[
    data`big[[n]][[All,2]],
    Greater
   ],
   {n,Length@labels}],
  PlotRange->Full,
  PlotLegends->labels,
  AxesLabel->{"Contributor Rank","Number of Commits"},
  ImageSize->Full,
  Joined->True,
  DataRange->{1,normalizationN}]


Export[exportDirectory<>"Full"<>exportType, g`full]
Export[exportDirectory<>"LogLogFull"<>exportType, g`fullLogLog]
Export[exportDirectory<>"FullNorm"<>exportType, g`fullNorm]
Export[exportDirectory<>"LogLogFullNorm"<>exportType, g`fullLogLogNorm]



